/*
 * OneLogin API
 * OpenAPI Specification for OneLogin
 *
 * The version of the OpenAPI document: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onelogin.client.model.AuthMethod;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Connector
 */
public class ConnectorTest {
    private final Connector model = new Connector();

    /**
     * Model tests for Connector
     */
    @Test
    public void testConnector() {
        // TODO: test Connector
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'iconUrl'
     */
    @Test
    public void iconUrlTest() {
        // TODO: test iconUrl
    }

    /**
     * Test the property 'authMethod'
     */
    @Test
    public void authMethodTest() {
        // TODO: test authMethod
    }

    /**
     * Test the property 'allowsNewParameters'
     */
    @Test
    public void allowsNewParametersTest() {
        // TODO: test allowsNewParameters
    }

}
