/*
 * OneLogin API
 * OpenAPI Specification for OneLogin
 *
 * The version of the OpenAPI document: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onelogin.client.model.GetEnrolledFactors200ResponseDataOtpDevicesInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetEnrolledFactors200ResponseData
 */
public class GetEnrolledFactors200ResponseDataTest {
    private final GetEnrolledFactors200ResponseData model = new GetEnrolledFactors200ResponseData();

    /**
     * Model tests for GetEnrolledFactors200ResponseData
     */
    @Test
    public void testGetEnrolledFactors200ResponseData() {
        // TODO: test GetEnrolledFactors200ResponseData
    }

    /**
     * Test the property 'otpDevices'
     */
    @Test
    public void otpDevicesTest() {
        // TODO: test otpDevices
    }

}
