/*
 * OneLogin API
 * OpenAPI Specification for OneLogin
 *
 * The version of the OpenAPI document: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onelogin.client.model.ConfigurationOidc;
import com.onelogin.client.model.SsoOidc;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OidcAppAllOf
 */
public class OidcAppAllOfTest {
    private final OidcAppAllOf model = new OidcAppAllOf();

    /**
     * Model tests for OidcAppAllOf
     */
    @Test
    public void testOidcAppAllOf() {
        // TODO: test OidcAppAllOf
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

    /**
     * Test the property 'sso'
     */
    @Test
    public void ssoTest() {
        // TODO: test sso
    }

}
