/*
 * OneLogin API
 * OpenAPI Specification for OneLogin
 *
 * The version of the OpenAPI document: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PrivilegePrivilegeStatementInner
 */
public class PrivilegePrivilegeStatementInnerTest {
    private final PrivilegePrivilegeStatementInner model = new PrivilegePrivilegeStatementInner();

    /**
     * Model tests for PrivilegePrivilegeStatementInner
     */
    @Test
    public void testPrivilegePrivilegeStatementInner() {
        // TODO: test PrivilegePrivilegeStatementInner
    }

    /**
     * Test the property 'effect'
     */
    @Test
    public void effectTest() {
        // TODO: test effect
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

}
