/*
 * OneLogin API
 * OpenAPI Specification for OneLogin
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: support@onelogin.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListAuthorizationServers200ResponseInnerConfiguration
 */
public class ListAuthorizationServers200ResponseInnerConfigurationTest {
    private final ListAuthorizationServers200ResponseInnerConfiguration model = new ListAuthorizationServers200ResponseInnerConfiguration();

    /**
     * Model tests for ListAuthorizationServers200ResponseInnerConfiguration
     */
    @Test
    public void testListAuthorizationServers200ResponseInnerConfiguration() {
        // TODO: test ListAuthorizationServers200ResponseInnerConfiguration
    }

    /**
     * Test the property 'resourceIdentifier'
     */
    @Test
    public void resourceIdentifierTest() {
        // TODO: test resourceIdentifier
    }

    /**
     * Test the property 'audiences'
     */
    @Test
    public void audiencesTest() {
        // TODO: test audiences
    }

}
