/*
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for User
 */
public class UserTest {
    private final User model = new User();

    /**
     * Model tests for User
     */
    @Test
    public void testUser() {
        // TODO: test User
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'firstname'
     */
    @Test
    public void firstnameTest() {
        // TODO: test firstname
    }

    /**
     * Test the property 'lastname'
     */
    @Test
    public void lastnameTest() {
        // TODO: test lastname
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'roleIds'
     */
    @Test
    public void roleIdsTest() {
        // TODO: test roleIds
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'directoryId'
     */
    @Test
    public void directoryIdTest() {
        // TODO: test directoryId
    }

    /**
     * Test the property 'trustedIdpId'
     */
    @Test
    public void trustedIdpIdTest() {
        // TODO: test trustedIdpId
    }

    /**
     * Test the property 'managerAdId'
     */
    @Test
    public void managerAdIdTest() {
        // TODO: test managerAdId
    }

    /**
     * Test the property 'managerUserId'
     */
    @Test
    public void managerUserIdTest() {
        // TODO: test managerUserId
    }

    /**
     * Test the property 'samaccountName'
     */
    @Test
    public void samaccountNameTest() {
        // TODO: test samaccountName
    }

    /**
     * Test the property 'memberOf'
     */
    @Test
    public void memberOfTest() {
        // TODO: test memberOf
    }

    /**
     * Test the property 'userprincipalname'
     */
    @Test
    public void userprincipalnameTest() {
        // TODO: test userprincipalname
    }

    /**
     * Test the property 'distinguishedName'
     */
    @Test
    public void distinguishedNameTest() {
        // TODO: test distinguishedName
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'activatedAt'
     */
    @Test
    public void activatedAtTest() {
        // TODO: test activatedAt
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    public void lastLoginTest() {
        // TODO: test lastLogin
    }

    /**
     * Test the property 'invitationSentAt'
     */
    @Test
    public void invitationSentAtTest() {
        // TODO: test invitationSentAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'preferredLocaleCode'
     */
    @Test
    public void preferredLocaleCodeTest() {
        // TODO: test preferredLocaleCode
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'invalidLoginAttempts'
     */
    @Test
    public void invalidLoginAttemptsTest() {
        // TODO: test invalidLoginAttempts
    }

    /**
     * Test the property 'lockedUntil'
     */
    @Test
    public void lockedUntilTest() {
        // TODO: test lockedUntil
    }

    /**
     * Test the property 'passwordChangedAt'
     */
    @Test
    public void passwordChangedAtTest() {
        // TODO: test passwordChangedAt
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'passwordConfirmation'
     */
    @Test
    public void passwordConfirmationTest() {
        // TODO: test passwordConfirmation
    }

    /**
     * Test the property 'passwordAlgorithm'
     */
    @Test
    public void passwordAlgorithmTest() {
        // TODO: test passwordAlgorithm
    }

    /**
     * Test the property 'salt'
     */
    @Test
    public void saltTest() {
        // TODO: test salt
    }

}
