/*
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onelogin.sdk;

import com.onelogin.sdk.ApiException;
import com.onelogin.sdk.model.ActivateFactorRequest;
import com.onelogin.sdk.model.AddAccessTokenClaimRequest;
import com.onelogin.sdk.model.AddClientAppRequest;
import com.onelogin.sdk.model.AddRoleUsers200ResponseInner;
import com.onelogin.sdk.model.AddScopeRequest;
import com.onelogin.sdk.model.AuthMethod;
import com.onelogin.sdk.model.ClientApp;
import com.onelogin.sdk.model.Connector;
import com.onelogin.sdk.model.CreateAuthorizationServerRequest;
import com.onelogin.sdk.model.CreateEnvironmentVariableRequest;
import com.onelogin.sdk.model.CreateRoles201ResponseInner;
import com.onelogin.sdk.model.CreateSessionLoginToken200Response;
import com.onelogin.sdk.model.CreateSessionLoginToken400Response;
import com.onelogin.sdk.model.CreateSessionLoginTokenRequest;
import com.onelogin.sdk.model.Device;
import com.onelogin.sdk.model.EnrollFactorRequest;
import com.onelogin.sdk.model.Envvar;
import com.onelogin.sdk.model.ErrorStatus;
import com.onelogin.sdk.model.FactorInner;
import com.onelogin.sdk.model.GenerateMfaToken200Response;
import com.onelogin.sdk.model.GenerateMfaToken422Response;
import com.onelogin.sdk.model.GenerateMfaTokenRequest;
import com.onelogin.sdk.model.GenerateSamlAssertionRequest;
import com.onelogin.sdk.model.GenerateToken200Response;
import com.onelogin.sdk.model.GenerateToken400Response;
import com.onelogin.sdk.model.GetAuthorizationServer200Response;
import com.onelogin.sdk.model.GetAvailableFactors200ResponseInner;
import com.onelogin.sdk.model.GetClientApps200ResponseInner;
import com.onelogin.sdk.model.GetEventById200Response;
import com.onelogin.sdk.model.GetEventTypes200Response;
import com.onelogin.sdk.model.GetEvents200Response;
import com.onelogin.sdk.model.GetGroupById200Response;
import com.onelogin.sdk.model.GetGroups200Response;
import com.onelogin.sdk.model.GetRateLimit200Response;
import com.onelogin.sdk.model.GetRiskScore200Response;
import com.onelogin.sdk.model.GetRiskScore400Response;
import com.onelogin.sdk.model.GetRiskScoreRequest;
import com.onelogin.sdk.model.GetScoreInsights200Response;
import com.onelogin.sdk.model.GetUserApps200ResponseInner;
import com.onelogin.sdk.model.Hook;
import com.onelogin.sdk.model.HookStatus;
import com.onelogin.sdk.model.Id;
import com.onelogin.sdk.model.ListAccessTokenClaims200ResponseInner;
import com.onelogin.sdk.model.ListActions200ResponseInner;
import com.onelogin.sdk.model.ListAppUsers200ResponseInner;
import com.onelogin.sdk.model.ListAuthorizationServers200ResponseInner;
import com.onelogin.sdk.model.ListConditionOperators200ResponseInner;
import com.onelogin.sdk.model.ListConditionValues200ResponseInner;
import com.onelogin.sdk.model.ListConditions200ResponseInner;
import com.onelogin.sdk.model.ListMappingConditionOperators200ResponseInner;
import com.onelogin.sdk.model.ListMappingConditions200ResponseInner;
import com.onelogin.sdk.model.ListScopes200ResponseInner;
import com.onelogin.sdk.model.Log;
import com.onelogin.sdk.model.Mapping;
import com.onelogin.sdk.model.Registration;
import com.onelogin.sdk.model.RemoveRoleUsersRequest;
import com.onelogin.sdk.model.RevokeTokenRequest;
import com.onelogin.sdk.model.RiskRule;
import com.onelogin.sdk.model.Role;
import com.onelogin.sdk.model.Rule;
import com.onelogin.sdk.model.RuleId;
import com.onelogin.sdk.model.Schema;
import com.onelogin.sdk.model.Schema1;
import com.onelogin.sdk.model.SetRoleApps200ResponseInner;
import com.onelogin.sdk.model.Status;
import com.onelogin.sdk.model.TrackEventRequest;
import com.onelogin.sdk.model.UpdateAuthorizationServer400Response;
import com.onelogin.sdk.model.UpdateClientAppRequest;
import com.onelogin.sdk.model.UpdateEnvironmentVariableRequest;
import com.onelogin.sdk.model.UpdateRole200Response;
import com.onelogin.sdk.model.User;
import com.onelogin.sdk.model.V1VerifyFactor200Response;
import com.onelogin.sdk.model.V1VerifyFactorRequest;
import com.onelogin.sdk.model.VerifyEnrollmentRequest;
import com.onelogin.sdk.model.VerifyFactorRequest;
import com.onelogin.sdk.model.VerifyFactorSaml200Response;
import com.onelogin.sdk.model.VerifyFactorSamlRequest;
import com.onelogin.sdk.model.VerifyFactorVoice200ResponseInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void activateFactorTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        ActivateFactorRequest activateFactorRequest = null;
        api.activateFactor(authorization, userId, activateFactorRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addAccessTokenClaimTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        AddAccessTokenClaimRequest addAccessTokenClaimRequest = null;
        Id response = api.addAccessTokenClaim(authorization, id, addAccessTokenClaimRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addClientAppTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        AddClientAppRequest addClientAppRequest = null;
        ClientApp response = api.addClientApp(authorization, id, addClientAppRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addRoleAdminsTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        List<Integer> requestBody = null;
        List<AddRoleUsers200ResponseInner> response = api.addRoleAdmins(authorization, roleId, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addRoleUsersTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        List<Integer> requestBody = null;
        List<AddRoleUsers200ResponseInner> response = api.addRoleUsers(authorization, roleId, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addScopeTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        AddScopeRequest addScopeRequest = null;
        Id response = api.addScope(authorization, id, addScopeRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkMappingSortTest() throws ApiException {
        String authorization = null;
        List<Integer> requestBody = null;
        List<Integer> response = api.bulkMappingSort(authorization, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkSortTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        List<Integer> requestBody = null;
        List<Integer> response = api.bulkSort(authorization, appId, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAppTest() throws ApiException {
        String authorization = null;
        Schema schema = null;
        Schema response = api.createApp(authorization, schema);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAuthorizationServerTest() throws ApiException {
        String authorization = null;
        CreateAuthorizationServerRequest createAuthorizationServerRequest = null;
        Id response = api.createAuthorizationServer(authorization, createAuthorizationServerRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createEnvironmentVariableTest() throws ApiException {
        String authorization = null;
        CreateEnvironmentVariableRequest createEnvironmentVariableRequest = null;
        Envvar response = api.createEnvironmentVariable(authorization, createEnvironmentVariableRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createHookTest() throws ApiException {
        String authorization = null;
        Hook hook = null;
        api.createHook(authorization, hook);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createMappingTest() throws ApiException {
        String authorization = null;
        Mapping mapping = null;
        Integer response = api.createMapping(authorization, mapping);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRiskRuleTest() throws ApiException {
        String authorization = null;
        RiskRule riskRule = null;
        api.createRiskRule(authorization, riskRule);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRolesTest() throws ApiException {
        String authorization = null;
        List<CreateRoles201ResponseInner> response = api.createRoles(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRuleTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Rule rule = null;
        RuleId response = api.createRule(authorization, appId, rule);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSessionLoginTokenTest() throws ApiException {
        String authorization = null;
        CreateSessionLoginTokenRequest createSessionLoginTokenRequest = null;
        String customAllowedOriginHeader1 = null;
        CreateSessionLoginToken200Response response = api.createSessionLoginToken(authorization, createSessionLoginTokenRequest, customAllowedOriginHeader1);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        String authorization = null;
        User user = null;
        String mappings = null;
        Boolean validatePolicy = null;
        User response = api.createUser(authorization, user, mappings, validatePolicy);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAccessTokenClaimTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        Integer claimId = null;
        api.deleteAccessTokenClaim(authorization, id, claimId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAppTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        api.deleteApp(authorization, appId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAppParameterTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Integer parameterId = null;
        api.deleteAppParameter(authorization, appId, parameterId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAuthorizationServerTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        api.deleteAuthorizationServer(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteEnvironmentVariableTest() throws ApiException {
        String authorization = null;
        String envvarId = null;
        api.deleteEnvironmentVariable(authorization, envvarId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteFactorTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        Integer deviceId = null;
        api.deleteFactor(authorization, userId, deviceId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteHookTest() throws ApiException {
        String authorization = null;
        String hookId = null;
        api.deleteHook(authorization, hookId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteMappingTest() throws ApiException {
        String authorization = null;
        Integer mappingId = null;
        api.deleteMapping(authorization, mappingId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRiskRuleTest() throws ApiException {
        String authorization = null;
        String riskRuleId = null;
        RiskRule response = api.deleteRiskRule(authorization, riskRuleId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRoleTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        api.deleteRole(authorization, roleId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRuleTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Integer ruleId = null;
        api.deleteRule(authorization, appId, ruleId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteScopeTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        Integer scopeId = null;
        api.deleteScope(authorization, id, scopeId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        api.deleteUser(authorization, userId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dryRunMappingTest() throws ApiException {
        String authorization = null;
        Integer mappingId = null;
        List<Integer> requestBody = null;
        List<Object> response = api.dryRunMapping(authorization, mappingId, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void enrollFactorTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        EnrollFactorRequest enrollFactorRequest = null;
        List<List<FactorInner>> response = api.enrollFactor(authorization, userId, enrollFactorRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateMfaTokenTest() throws ApiException {
        String authorization = null;
        GenerateMfaTokenRequest generateMfaTokenRequest = null;
        GenerateMfaToken200Response response = api.generateMfaToken(authorization, generateMfaTokenRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateSamlAssertionTest() throws ApiException {
        String authorization = null;
        GenerateSamlAssertionRequest generateSamlAssertionRequest = null;
        api.generateSamlAssertion(authorization, generateSamlAssertionRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateTokenTest() throws ApiException {
        String clientId = null;
        String clientSecret = null;
        String grantType = null;
        GenerateToken200Response response = api.generateToken(clientId, clientSecret, grantType);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAppTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Schema response = api.getApp(authorization, appId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAuthorizationServerTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        GetAuthorizationServer200Response response = api.getAuthorizationServer(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailableFactorsTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        List<GetAvailableFactors200ResponseInner> response = api.getAvailableFactors(authorization, userId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getClientAppsTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        List<GetClientApps200ResponseInner> response = api.getClientApps(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEnrolledFactorsTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        List<Device> response = api.getEnrolledFactors(authorization, userId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEnvironmentVariableTest() throws ApiException {
        String authorization = null;
        String envvarId = null;
        Envvar response = api.getEnvironmentVariable(authorization, envvarId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventByIdTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        GetEventById200Response response = api.getEventById(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventTypesTest() throws ApiException {
        GetEventTypes200Response response = api.getEventTypes();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventsTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        String fields = null;
        String until = null;
        String since = null;
        Integer limit = null;
        String sort = null;
        Integer clientId = null;
        String createdAt = null;
        String directoryId = null;
        List<Integer> eventTypeId = null;
        Integer id = null;
        String resolution = null;
        GetEvents200Response response = api.getEvents(authorization, userId, fields, until, since, limit, sort, clientId, createdAt, directoryId, eventTypeId, id, resolution);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGroupByIdTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        GetGroupById200Response response = api.getGroupById(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGroupsTest() throws ApiException {
        String authorization = null;
        String fields = null;
        String until = null;
        String since = null;
        Integer limit = null;
        String sort = null;
        Integer id = null;
        GetGroups200Response response = api.getGroups(authorization, fields, until, since, limit, sort, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getHookTest() throws ApiException {
        String authorization = null;
        String hookId = null;
        Hook response = api.getHook(authorization, hookId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLogsTest() throws ApiException {
        String authorization = null;
        String hookId = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String requestId = null;
        String correlationId = null;
        List<Log> response = api.getLogs(authorization, hookId, limit, page, cursor, requestId, correlationId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMappingTest() throws ApiException {
        String authorization = null;
        Integer mappingId = null;
        Mapping response = api.getMapping(authorization, mappingId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRateLimitTest() throws ApiException {
        String authorization = null;
        GetRateLimit200Response response = api.getRateLimit(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRiskRuleTest() throws ApiException {
        String authorization = null;
        String riskRuleId = null;
        api.getRiskRule(authorization, riskRuleId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRiskScoreTest() throws ApiException {
        String authorization = null;
        GetRiskScoreRequest getRiskScoreRequest = null;
        GetRiskScore200Response response = api.getRiskScore(authorization, getRiskScoreRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRoleTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        Role response = api.getRole(authorization, roleId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRoleAdminsTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String name = null;
        Boolean includeUnassigned = null;
        List<Schema1> response = api.getRoleAdmins(authorization, roleId, limit, page, cursor, name, includeUnassigned);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRoleAppsTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        Boolean assigned = null;
        List<Schema> response = api.getRoleApps(authorization, roleId, limit, page, cursor, assigned);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRoleUsersTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String name = null;
        Boolean includeUnassigned = null;
        List<Schema1> response = api.getRoleUsers(authorization, roleId, limit, page, cursor, name, includeUnassigned);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRuleTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Integer ruleId = null;
        Rule response = api.getRule(authorization, appId, ruleId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getScoreInsightsTest() throws ApiException {
        String authorization = null;
        String before = null;
        String after = null;
        GetScoreInsights200Response response = api.getScoreInsights(authorization, before, after);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        User response = api.getUser(authorization, userId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserAppsTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        Boolean ignoreVisibility = null;
        List<GetUserApps200ResponseInner> response = api.getUserApps(authorization, userId, ignoreVisibility);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAccessTokenClaimsTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        List<ListAccessTokenClaims200ResponseInner> response = api.listAccessTokenClaims(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listActionValuesTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        String actionValue = null;
        List<ListConditionValues200ResponseInner> response = api.listActionValues(authorization, appId, actionValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listActionsTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        List<ListActions200ResponseInner> response = api.listActions(authorization, appId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAppUsersTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        List<ListAppUsers200ResponseInner> response = api.listAppUsers(authorization, appId, limit, page, cursor);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAppsTest() throws ApiException {
        String authorization = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String name = null;
        Integer connectorId = null;
        AuthMethod authMethod = null;
        List<Schema> response = api.listApps(authorization, limit, page, cursor, name, connectorId, authMethod);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAuthorizationServersTest() throws ApiException {
        String authorization = null;
        List<ListAuthorizationServers200ResponseInner> response = api.listAuthorizationServers(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listConditionOperatorsTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        String conditionValue = null;
        List<ListConditionOperators200ResponseInner> response = api.listConditionOperators(authorization, appId, conditionValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listConditionValuesTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        String conditionValue = null;
        List<ListConditionValues200ResponseInner> response = api.listConditionValues(authorization, appId, conditionValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listConditionsTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        List<ListConditions200ResponseInner> response = api.listConditions(authorization, appId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listConnectorsTest() throws ApiException {
        String authorization = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String name = null;
        AuthMethod authMethod = null;
        List<Connector> response = api.listConnectors(authorization, limit, page, cursor, name, authMethod);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listEnvironmentVariablesTest() throws ApiException {
        String authorization = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        List<Envvar> response = api.listEnvironmentVariables(authorization, limit, page, cursor);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listHooksTest() throws ApiException {
        String authorization = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        List<Hook> response = api.listHooks(authorization, limit, page, cursor);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMappingActionValuesTest() throws ApiException {
        String authorization = null;
        String actionValue = null;
        List<ListConditionValues200ResponseInner> response = api.listMappingActionValues(authorization, actionValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMappingActionsTest() throws ApiException {
        String authorization = null;
        List<ListActions200ResponseInner> response = api.listMappingActions(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMappingConditionOperatorsTest() throws ApiException {
        String authorization = null;
        String conditionValue = null;
        List<ListMappingConditionOperators200ResponseInner> response = api.listMappingConditionOperators(authorization, conditionValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMappingConditionValuesTest() throws ApiException {
        String authorization = null;
        String conditionValue = null;
        List<ListConditionValues200ResponseInner> response = api.listMappingConditionValues(authorization, conditionValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMappingConditionsTest() throws ApiException {
        String authorization = null;
        List<ListMappingConditions200ResponseInner> response = api.listMappingConditions(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMappingsTest() throws ApiException {
        String authorization = null;
        Boolean enabled = null;
        String hasCondition = null;
        String hasConditionType = null;
        String hasAction = null;
        String hasActionType = null;
        List<Mapping> response = api.listMappings(authorization, enabled, hasCondition, hasConditionType, hasAction, hasActionType);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listRiskRulesTest() throws ApiException {
        String authorization = null;
        api.listRiskRules(authorization);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listRolesTest() throws ApiException {
        String authorization = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String name = null;
        String appId = null;
        String fields = null;
        List<Role> response = api.listRoles(authorization, limit, page, cursor, name, appId, fields);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listRulesTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Boolean enabled = null;
        String hasCondition = null;
        String hasConditionType = null;
        String hasAction = null;
        String hasActionType = null;
        List<Rule> response = api.listRules(authorization, appId, enabled, hasCondition, hasConditionType, hasAction, hasActionType);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listScopesTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        List<ListScopes200ResponseInner> response = api.listScopes(authorization, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUsersTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Integer limit = null;
        Integer page = null;
        String cursor = null;
        String createdSince = null;
        String createdUntil = null;
        String updatedSince = null;
        String updatedUntil = null;
        String lastLoginSince = null;
        String lastLoginUntil = null;
        String firstname = null;
        String lastname = null;
        String email = null;
        String username = null;
        String samaccountname = null;
        String directoryId = null;
        String externalId = null;
        String userIds = null;
        String customAttributesLeftCurlyBracketAttributeNameRightCurlyBracket = null;
        String fields = null;
        List<User> response = api.listUsers(authorization, appId, limit, page, cursor, createdSince, createdUntil, updatedSince, updatedUntil, lastLoginSince, lastLoginUntil, firstname, lastname, email, username, samaccountname, directoryId, externalId, userIds, customAttributesLeftCurlyBracketAttributeNameRightCurlyBracket, fields);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeClientAppTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        Integer clientAppId = null;
        api.removeClientApp(authorization, id, clientAppId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeRoleAdminsTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        RemoveRoleUsersRequest removeRoleUsersRequest = null;
        api.removeRoleAdmins(authorization, roleId, removeRoleUsersRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeRoleUsersTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        RemoveRoleUsersRequest removeRoleUsersRequest = null;
        api.removeRoleUsers(authorization, roleId, removeRoleUsersRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revokeTokenTest() throws ApiException {
        String authorization = null;
        RevokeTokenRequest revokeTokenRequest = null;
        GenerateToken400Response response = api.revokeToken(authorization, revokeTokenRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setRoleAppsTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        List<Integer> requestBody = null;
        List<SetRoleApps200ResponseInner> response = api.setRoleApps(authorization, roleId, requestBody);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void trackEventTest() throws ApiException {
        String authorization = null;
        TrackEventRequest trackEventRequest = null;
        api.trackEvent(authorization, trackEventRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAccessTokenClaimTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        Integer claimId = null;
        AddAccessTokenClaimRequest addAccessTokenClaimRequest = null;
        Id response = api.updateAccessTokenClaim(authorization, id, claimId, addAccessTokenClaimRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAppTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Schema schema = null;
        Schema response = api.updateApp(authorization, appId, schema);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAuthorizationServerTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        CreateAuthorizationServerRequest createAuthorizationServerRequest = null;
        Id response = api.updateAuthorizationServer(authorization, id, createAuthorizationServerRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateClientAppTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        Integer clientAppId = null;
        UpdateClientAppRequest updateClientAppRequest = null;
        ClientApp response = api.updateClientApp(authorization, id, clientAppId, updateClientAppRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateEnvironmentVariableTest() throws ApiException {
        String authorization = null;
        String envvarId = null;
        UpdateEnvironmentVariableRequest updateEnvironmentVariableRequest = null;
        Envvar response = api.updateEnvironmentVariable(authorization, envvarId, updateEnvironmentVariableRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateHookTest() throws ApiException {
        String authorization = null;
        String hookId = null;
        Hook hook = null;
        Hook response = api.updateHook(authorization, hookId, hook);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateMappingTest() throws ApiException {
        String authorization = null;
        Integer mappingId = null;
        Mapping mapping = null;
        Integer response = api.updateMapping(authorization, mappingId, mapping);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRiskRuleTest() throws ApiException {
        String authorization = null;
        String riskRuleId = null;
        RiskRule riskRule = null;
        RiskRule response = api.updateRiskRule(authorization, riskRuleId, riskRule);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRoleTest() throws ApiException {
        String authorization = null;
        Integer roleId = null;
        Role role = null;
        UpdateRole200Response response = api.updateRole(authorization, roleId, role);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateRuleTest() throws ApiException {
        String authorization = null;
        Integer appId = null;
        Integer ruleId = null;
        Rule rule = null;
        RuleId response = api.updateRule(authorization, appId, ruleId, rule);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateScopeTest() throws ApiException {
        String authorization = null;
        Integer id = null;
        Integer scopeId = null;
        AddScopeRequest addScopeRequest = null;
        Id response = api.updateScope(authorization, id, scopeId, addScopeRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        User user = null;
        String mappings = null;
        Boolean validatePolicy = null;
        User response = api.updateUser(authorization, userId, user, mappings, validatePolicy);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1VerifyFactorTest() throws ApiException {
        String authorization = null;
        V1VerifyFactorRequest v1VerifyFactorRequest = null;
        String customAllowedOriginHeader1 = null;
        V1VerifyFactor200Response response = api.v1VerifyFactor(authorization, v1VerifyFactorRequest, customAllowedOriginHeader1);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyEnrollmentTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        Integer registrationId = null;
        VerifyEnrollmentRequest verifyEnrollmentRequest = null;
        List<Registration> response = api.verifyEnrollment(authorization, userId, registrationId, verifyEnrollmentRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyEnrollmentVoiceProtectTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        Integer registrationId = null;
        List<Registration> response = api.verifyEnrollmentVoiceProtect(authorization, userId, registrationId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyFactorTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        Integer verificationId = null;
        VerifyFactorRequest verifyFactorRequest = null;
        GenerateToken400Response response = api.verifyFactor(authorization, userId, verificationId, verifyFactorRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyFactorSamlTest() throws ApiException {
        String authorization = null;
        VerifyFactorSamlRequest verifyFactorSamlRequest = null;
        VerifyFactorSaml200Response response = api.verifyFactorSaml(authorization, verifyFactorSamlRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyFactorVoiceTest() throws ApiException {
        String authorization = null;
        Integer userId = null;
        Integer verificationId = null;
        List<VerifyFactorVoice200ResponseInner> response = api.verifyFactorVoice(authorization, userId, verificationId);
        // TODO: test validations
    }

}
